apiVersion: v1
current-context: rcp-caas-prod
kind: Config
preferences: {}
clusters:
# Cluster RCP Prod
- name: caas-prod.rcp.epfl.ch
  cluster:
    server: https://caas-prod.rcp.epfl.ch:443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRHdwSElpTmQrVUV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1UUXdPVFU1TWpkYUZ3MHpOREEyTVRJeE1EQTBNamRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURvOHJDRjNjeXdRRTlxTVpEOHNGTXo2K0FzSEpnWi81WVNwMGNhWHNKd0JWUERneGdwRGZKY0hnYXYKS2tOdVhTNGpBN1VrZkg1amZXQitvdytpamN3OUR4cjV6STB2TUNReWtzYk9kMVFFMis0Q0J1U0JXU01Gc1pYZQp2T01SanltN056SytxWkVldHpxR0M0bU5LdU9qbC92cGd4ZDNuM2Y2L3loRHhockp2bkVWKzZlUE5icWpDZURZCld1VWFZdUYxRmM4QnZHN0hma3FYRlRWWVdlNkpNa3JSbDQxOVo5a2diNnIvUFNZVzZqdDhhNThTSGNHSVhnTFcKOTBta3BFb1JCMENOSG0wQllEQjdjNFJxMmdyaWtZTUlldGM0eXk2L3NSdFp6NzFiTUQrM2ZDNk92NDdvOXUzWgpld0VWeEJ4dG11ZkVvVGduVEVyNXFYMlhxWFZMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSazdCMm84a3cxcyt0Ny9ZaGxmV1h1MnR6TkdEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXFOdnQrR01lTwp6QnZZZEQ2SExCakFVeWc1czd0TDgzOVltd0RhRXBseG45ZlBRdUV6UW14cnEwUEoxcnVZNnRvRks1SEN4RFVzCmJDN3R3WlMzaVdNNXQ5NEJveHJGVC92c3QrQmtzbWdvTGM2T0N1MitYcngyMUg3UnFLTnNVR01LN2tFdGN6cHgKeXUrYTB6T0tISEUxNWFSVENPbklzQ1pXaTRhVFhIZ00zQ2U4VEhBMXRxaW9pREFHMVFUQXNhNXhTeVM3RWlUSQpDYi9xbktPRlVvM3V3bkRocWljRTU3dE1LTjliRE8rV3hNMzVxT2lBZXVXOUVnc2JlOFA5aDY2NG1tK1QzbjY0ClJNL1l1NHhmcDZwMHMvdGZyZTVjaUFvT0dGekYyRmVKek5PYm1vRkVseUtKc0RwbEorcWFTVXlaL2NtNWRIYUUKQVUxOVMrUWpFc1cvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
# Cluster IC
- name: ic-caas
  cluster:
    server: https://ic-caas.epfl.ch:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdLekNDQlJPZ0F3SUJBZ0lRQWVhbjJ4T1BQcXdyQ3RUcWZ0VUFiREFOQmdrcWhraUc5dzBCQVFzRkFEQloKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVRNd01RWURWUVFERXlwRQphV2RwUTJWeWRDQkhiRzlpWVd3Z1J6SWdWRXhUSUZKVFFTQlRTRUV5TlRZZ01qQXlNQ0JEUVRFd0hoY05NalF3Ck56QTBNREF3TURBd1doY05NalF4TWpNd01qTTFPVFU1V2pCd01Rc3dDUVlEVlFRR0V3SkRTREVSTUE4R0ExVUUKQnhNSVRHRjFjMkZ1Ym1VeE5EQXlCZ05WQkFvTUs4T0pZMjlzWlNCd2IyeDVkR1ZqYUc1cGNYVmxJR2JEcVdURApxWEpoYkdVZ1pHVWdUR0YxYzJGdWJtVXhHREFXQmdOVkJBTVREMmxqTFdOaFlYTXVaWEJtYkM1amFEQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSDdGbmd3cEdBRjJkbkh4d0JCNkRmNUpkZ2J0MERKanJlWDkKYml4d0s4emRaZWIwMzgwZkRrMVFUSDRJMVJjNmRZZ1F0Q2FZNXhLdkxLWlZJRUNQdmoramdnT2hNSUlEblRBZgpCZ05WSFNNRUdEQVdnQlIwaFlEQVpzZmZOOTdQdlNrM3FnTWR2dTNORnpBZEJnTlZIUTRFRmdRVXZkdGg5NGpwCmd2VTJnaGN0OTR1UXBjdTNIUFl3TVFZRFZSMFJCQ293S0lJUGFXTXRZMkZoY3k1bGNHWnNMbU5vZ2hWcFkzWnQKTURFNE9TNTRZV0Z6TG1Wd1ptd3VZMmd3UGdZRFZSMGdCRGN3TlRBekJnWm5nUXdCQWdJd0tUQW5CZ2dyQmdFRgpCUWNDQVJZYmFIUjBjRG92TDNkM2R5NWthV2RwWTJWeWRDNWpiMjB2UTFCVE1BNEdBMVVkRHdFQi93UUVBd0lECmlEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3Z1o4R0ExVWRId1NCbHpDQmxEQkkKb0VhZ1JJWkNhSFIwY0RvdkwyTnliRE11WkdsbmFXTmxjblF1WTI5dEwwUnBaMmxEWlhKMFIyeHZZbUZzUnpKVQpURk5TVTBGVFNFRXlOVFl5TURJd1EwRXhMVEV1WTNKc01FaWdScUJFaGtKb2RIUndPaTh2WTNKc05DNWthV2RwClkyVnlkQzVqYjIwdlJHbG5hVU5sY25SSGJHOWlZV3hITWxSTVUxSlRRVk5JUVRJMU5qSXdNakJEUVRFdE1TNWoKY213d2dZY0dDQ3NHQVFVRkJ3RUJCSHN3ZVRBa0JnZ3JCZ0VGQlFjd0FZWVlhSFIwY0RvdkwyOWpjM0F1WkdsbgphV05sY25RdVkyOXRNRkVHQ0NzR0FRVUZCekFDaGtWb2RIUndPaTh2WTJGalpYSjBjeTVrYVdkcFkyVnlkQzVqCmIyMHZSR2xuYVVObGNuUkhiRzlpWVd4SE1sUk1VMUpUUVZOSVFUSTFOakl3TWpCRFFURXRNUzVqY25Rd0RBWUQKVlIwVEFRSC9CQUl3QURDQ0FYMEdDaXNHQVFRQjFua0NCQUlFZ2dGdEJJSUJhUUZuQUhZQWR2K0lQd3EyKzVWUgp3bUhNOVllNk5MU2t6YnNwM0doQ0NwL21aMHhhT25RQUFBR1FmUHozcGdBQUJBTUFSekJGQWlFQTBuakJGbEtvCkJQNGxZSDFFTTJYYTE2czUxdW9GL3UxQloyaG9WQ1creUpvQ0lHMzB6NkpRUWlDTG5SZTZRQ1N2cklGc0J2YXEKTzJJUHNKMmhMRmlXU1VXOUFIWUEycmEvYXorMXRpS2ZtOEs3WEd2b2NKRnhiTHRSaElVMHZhUTlNRWpYKzZzQQpBQUdRZlB6M2FnQUFCQU1BUnpCRkFpRUEzVDI1bVlWZ3NNcXNMN1hVK0hBeWV3VWVkV1l3cnJSZEM1YmNsWjR0CjVFTUNJQW9uN1VKSlFlOEFJZk1ndWhTUDNHdm5GOWFMUjFWNWI3bE5vYnhEcURqWEFIVUFQeGRMVDljaVIxaVUKSFdVY2hMNE5FdTJRTjM4ZmhXcnJ3YjhvaGV6NFpHNEFBQUdRZlB6NEJnQUFCQU1BUmpCRUFpQTN5WXZUMGNWYQpyMDZZQndsRXZ2cFZ5bmhWSVlCaE9RNU1OT05tMjkzZ2NBSWdBU1JzSTFybEY4VWNoMXI5b2hIZzBLT1VEL1liCjlBUTZvNWFKZWl5dTYzd3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSjVIMVFaSUxRdDZxeUlNb2xhNkgrZ0gKN0JTYU9OeGlySFBETEZ3b0RtN2tIRU1NTnViTW8rdFlSYThZSmJiWVhOUjErUFFpRGNNOXVZMnFjWXhkdHZLNApMMDhEdjlWUC8vY2VWeEkrNmRPRUlQNXRRS01pZE51L09KTU9KWW1yZnEwY1Uzb1RPQlZCYVBBWWN3empzTHdGCkh3QUgyR0RDM1NzdXdUZjVwRWdTS3FGbG9vdVhrWlF0UkhIVytrM3YzcGhXeE1zZEY5R3JMUGJkcFhSWnFyTXUKdXJpS2FNRUc3TGVWcGQ2czNKT1JCTmRYcEwxZXA4eFdYKzVQdEZxUDRzR0trc3VuTjh6SU5tR2oyRVd0V3ZzeQpYQm5iVjhnZTZPeStRRDM3Zk5sZUJFdTByUnVyZjBHNEFGTFlsVTVqNk85cnVLL0NZYlJSM0NncGZlZEM0bE09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
users:
# Authenticated user on RunAI RCP
- name: runai-rcp-authenticated-user
  user:
    auth-provider:
      name: oidc
      config:
        airgapped: "true"
        auth-flow: remote-browser
        client-id: runai-cli
        idp-issuer-url: https://app.run.ai/auth/realms/rcpepfl
        realm: rcpepfl
        redirect-uri: https://rcpepfl.run.ai/oauth-code
# Authenticated user on RunAI IC
- name: runai-authenticated-user
  user:
    auth-provider:
      config:
        airgapped: "true"
        auth-flow: remote-browser
        client-id: runai-cli
        idp-issuer-url: https://app.run.ai/auth/realms/epfl
        realm: epfl
        redirect-uri: https://epfl.run.ai/oauth-code
      name: oidc
contexts:
# Contexts (a context a cluster associated with a user)
- name: rcp-caas-prod
  context:
    cluster: caas-prod.rcp.epfl.ch
    user: runai-rcp-authenticated-user
- name: ic-caas
  context:
    cluster: ic-caas
    user: runai-authenticated-user
